services:
  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:latest
    restart: always
    depends_on:
      - redis
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances
    
  redis:
    image: redis:latest
    networks:
      - evolution-net
    container_name: redis
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - evolution_redis:/data
    ports:
      - 127.0.0.1:6379:6379 # Restrito ao host local
  
  postgres:
    container_name: postgres
    image: postgres:15
    networks:
      - evolution-net
    command: ["postgres", "-c", "max_connections=1000"]
    restart: always
    ports:
      - 127.0.0.1:5432:5432 # Restrito ao host local
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
  
  pgadmin:
    image: dpage/pgadmin4:latest
    networks:
      - evolution-net
    volumes:
      - pgadmin_data:/var/lib/pgadmin # Restrito ao host local
    ports:
      - 127.0.0.1:4000:80
    env_file:
      - .env

volumes:
  evolution_instances:
  evolution_redis:
  postgres_data:
  pgadmin_data:

networks:
  evolution-net:
    name: evolution-net
    driver: bridge